version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
    healthcheck:
      test: curl --fail http://localhost:3000/
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - overlay

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - overlay

networks:
  overlay:
