using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SocialMedia.Data;

[AutoTimestamp]
public class Post
{
    public Guid Id { get; set; }
    [Required]
    [MaxLength(255)]
    public string Content { get; set; }
    [Required]
    public int Likes { get; set; }

    [Required]
    public User? Author { get; set; }

    [IgnoreDataMember]
    public virtual ICollection<Comment> Comments { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public Post(Guid id, string content)
    {
        var now = DateTime.UtcNow;
        Id = id;
        Content = content;
        Likes = 0;
        Author = null;
        Comments = new List<Comment>();
    }

    internal static void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Post>().Property(x => x.Id).AutoGenerated();
    }
}
