using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace SocialMedia.Data;

internal static class PropertyBuilderAutoGenerated
{
    public static PropertyBuilder<TProperty> AutoGenerated<TProperty>(this PropertyBuilder<TProperty> propertyBuilder)
    {
        return propertyBuilder
            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
            .HasAnnotation("MySql:ValueGeneratedOnAdd", true)
            .HasAnnotation("Sqlite:Autoincrement", true);
    }
}