using Microsoft.EntityFrameworkCore;

namespace SocialMedia.Data;

public class User
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }

    public User(int id, string username, string password, string role)
    {
        Id = id;
        Username = username;
        Password = password;
        Role = role;
    }

    internal static void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<User>().Property(x => x.Id).AutoGenerated();
    }
}
