using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SocialMedia.Data;

[Index("Username", IsUnique = true)]
public class User
{
    public Guid Id { get; set; }
    [Required]
    [MinLength(3)]
    [MaxLength(30)]
    public string Username { get; set; }
    [Required]
    [MinLength(8)]
    [MaxLength(30)]
    [IgnoreDataMember]
    public string Password { get; set; }
    [Required]
    public string Role { get; set; }

    public User(Guid id, string username, string password, string role)
    {
        Id = id;
        Username = username;
        Password = password;
        Role = role;
    }

    internal static void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<User>().Property(x => x.Id).AutoGenerated();
    }
}
